class _BotCommands:
    def __init__(self):
        self.StartCommand = 'startwb'
        self.MirrorCommand = 'mirrorwb'
        self.UnzipMirrorCommand = 'unzipmirrorwb'
        self.TarMirrorCommand = 'tarmirrorwb'
        self.ZipMirrorCommand = 'zipmirrorwb'
        self.CancelMirror = 'cancelwb'
        self.CancelAllCommand = 'cancelallwb'
        self.ListCommand = 'listwb'
        self.StatusCommand = 'statuswb'
        self.AuthorizedUsersCommand = 'userswb'
        self.AuthorizeCommand = 'authorizewb'
        self.UnAuthorizeCommand = 'unauthorizewb'
        self.AddSudoCommand = 'addsudowb'
        self.RmSudoCommand = 'rmsudowb'
        self.PingCommand = 'pingwb'
        self.RestartCommand = 'restartwb'
        self.StatsCommand = 'statswb'
        self.HelpCommand = 'helpwb'
        self.LogCommand = 'logwb'
        self.SpeedCommand = 'speedtestwb'
        self.CloneCommand = 'clonewb'
        self.CountCommand = 'countwb'
        self.WatchCommand = 'watchwb'
        self.TarWatchCommand = 'tarwatchwb'
        self.DeleteCommand = 'delwb'
        self.ConfigMenuCommand = 'configwb'
        self.ShellCommand = 'shellwb'
        self.UpdateCommand = 'updatewb'
        self.ExecHelpCommand = 'exechelpwb'
        self.TsHelpCommand = 'tshelpwb'

BotCommands = _BotCommands()
